---
title: "Bilmerker"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE
  )

library(tidyverse)
library(gt)
library(gtExtras)

#
```

```{r data, include=FALSE}
# Common brands ----
vehicle_brands_norway <-
  readRDS(
    "C:/Users/snohan/Desktop/vehicle_brand_counts.rds"
  )

common_vehicle_brands_norway <-
  vehicle_brands_norway |> 
  dplyr::filter(
    n >= 1000
  ) |> 
  dplyr::arrange(
    vehicle_brand
  ) |> 
  # Removing brands not likely to be seen
  dplyr::filter(
    !(vehicle_brand %in% c(
      "SMART",
      "ZETOR",
      "MCCORMICK",
      "CARTHAGO",
      "ADRIA",
      "RAPIDO",
      "CHALLENGER",
      "DETHLEFFS",
      "CAPRON",
      "CASE",
      "BURSTNER",
      "HYMER"
    ))
  )


# Logos ----
logo_folder <- 
  "C:/Users/snohan/Documents/R-prosjekter/car_logos"

list_logos <-
  list.files(logo_folder)


# Brands and logos
common_vehicles <-
  tibble::tibble(
    name = list_logos,
    path = paste0(logo_folder, "/", name)
  ) |> 
  dplyr::mutate(
    name = stringr::str_replace(name, ".png", ""),
    vehicle_brand = stringr::str_to_upper(name)
  ) |> 
  dplyr::full_join(
    common_vehicle_brands_norway,
    by = "vehicle_brand"
  ) |> 
  dplyr::filter(
    !is.na(n)
  )



```

```{r long_table}
# tibble::tibble(
#     name = list_logos,
#     path = paste0(logo_folder, "/", name)
#   ) |> 
#   dplyr::mutate(
#     name = stringr::str_replace(name, ".png", "")
#   ) |> 
#   dplyr::arrange(
#     name
#   ) |> 
#   gt::gt() |> 
#   gtExtras::gt_img_rows(
#       columns = path,
#       height = 80
#   )
```


```{r wide_table}
dplyr::bind_cols(
  common_vehicles$path[1:10],
  common_vehicles$path[11:20],
  common_vehicles$path[21:30],
  common_vehicles$path[31:40],
  common_vehicles$path[41:50],
  .name_repair = "unique"
) |> 
gt::gt() |> 
gtExtras::gt_img_rows(
    columns = "...1",
    height = 80
) |> 
  gtExtras::gt_img_rows(
    columns = "...2",
    height = 80
) |> 
  gtExtras::gt_img_rows(
    columns = "...3",
    height = 80
) |> 
  gtExtras::gt_img_rows(
    columns = "...4",
    height = 80
) |> 
  gtExtras::gt_img_rows(
    columns = "...5",
    height = 80
) |> 
gt::cols_width(
  everything() ~ px(130)
)
```

